# build stage
FROM golang:1.16-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o main .

# final stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["/app/main"]
